---

# Add customized pull-secret, imageContentSources, and certificate-authority

- block:
    - name: Create SSH keys
      openssh_keypair:
        path: ~/.ssh/id_rsa
      register: r_host_prep_create_ssh_keys

    - name: Set the SSH public key fact
      set_fact:
        ssh_public_key: "{{ r_host_prep_create_ssh_keys.public_key | trim }}"
  when: ssh_public_key is undefined

- name: Create OpenShift install-config.yaml for disconnected environments
  template:
    src: install-config.yaml.j2
    dest: "{{ openshift_install_dir }}/{{ item }}"
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    mode: 0644
  loop:
    - install-config.yaml
    - install-config.backup.yaml
  #when: not r_stat_ignition_files.stat.exists

- name: Create upgrade manifest for disconnected environments
  template:
    src: upgrade-manifest.yaml.j2
    dest: "{{ openshift_install_dir }}/upgrade-manifest.yaml"
    owner: "{{ ansible_user_uid | int }}"
    group: "{{ ansible_user_gid | int }}"
    mode: 0644
