galaxy_info:
  author: John Call
  description: An Ansible role to create a registry mirror when installing OCP disconnected
  company: Red Hat

  issue_tracker_url: https://github.com/jaredhocutt/openshift4-deploy/issues

  license: WTFPL

  min_ansible_version: 2.9

  platforms:
    - name: Fedora
      versions:
        - 31
        - 32

  galaxy_tags:
    - ocp
    - mirror
    - disconnected
    - registry

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
