---

- hosts: localhost
  tags: always
  gather_facts: no
  tasks:
    - name: Add bastion to inventory
      add_host:
        name: bastion
        ansible_host: "{{ r_terraform_apply.outputs.bastion_eip.value.public_ip }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ keypair_path }}"
        terraform_outputs: "{{ r_terraform_apply.outputs }}"
      changed_when: no
      when: r_terraform_apply.outputs.bastion_eip.value.public_ip is defined

    - name: Add bastion to inventory (override)
      add_host:
        name: bastion
        ansible_host: "{{ bastion_fqdn_override }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ keypair_path }}"
      changed_when: no
      when: r_terraform_apply.outputs.bastion_eip.value.public_ip is not defined
    
    - name: Wait for bastion to boot
      wait_for:
        host: "{{ hostvars['bastion'].ansible_host }}"
        port: 22
        search_regex: OpenSSH
      delegate_to: localhost


- hosts: bastion
  gather_facts: yes
  tasks:
    - import_role:
        name: host_prep_mirror
